/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucr.parchisc5e852.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Lenovo
 */
public class GUIinicio extends javax.swing.JFrame {
    
    
    /**
     * Creates new form GUIinicio
     */
    public GUIinicio()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtColorSeleccion = new javax.swing.JTextField();
        btnJugar = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtColorSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, -1));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesMenu/BotonJugar.png"))); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.setOpaque(true);
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 80, 30));

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesMenu/BotonInstrucciones.png"))); // NOI18N
        btnInstrucciones.setText("Instrucciones");
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 80, 30));

        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesMenu/BotonHistoria.png"))); // NOI18N
        btnHistoria.setText("Historia");
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, 30));

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesMenu/BotonEnviar.png"))); // NOI18N
        btnEnviar.setText("Enviar");
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 80, 30));

        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesMenu/BotonCreditos.png"))); // NOI18N
        btnCreditos.setText("Creditos");
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Copia de Recurso 1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void listen(ActionListener controller)
    {
        this.btnCreditos.addActionListener(controller);
        this.btnEnviar.addActionListener(controller);
        this.btnHistoria.addActionListener(controller);
        this.btnInstrucciones.addActionListener(controller);
        this.btnJugar.addActionListener(controller);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtColorSeleccion;
    // End of variables declaration//GEN-END:variables
}
