/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.proyectoparchis.view;

import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import ucr.ac.cr.proyectoparchis.controller.GameController;

/**
 *
 * @author jeanmarco
 */
public class BoardPanel extends javax.swing.JPanel {
//en esta clase esta el tablero de parchis
    /**
     * Creates new form BoardPanel
     */
    private ImageIcon boardGraphic;
    private GameController gameController;
    
    public BoardPanel() {
        initComponents();
       this.boardGraphic=new ImageIcon("./src/main/resources/imagenes/tableroDeParchisDemo.png");
    }
    
    public void listen(ActionListener controller)
    {
        addMouseListener((MouseListener) controller);
    }
    
    public void setController(GameController controller)
    {
        this.gameController=controller;
        this.listen(controller);
    }
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        this.boardGraphic.paintIcon(this, g, 0, 80);//es lo que dibuja el tablero, los numeros son las coordenadas
        if(gameController!=null)
        {
        this.gameController.draw(this, g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
