/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.proyectoparchis.view;

import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import ucr.ac.cr.proyectoparchis.controller.GameController;

/**
 *
 * @author jeanmarco
 */
public class ControlPanel extends javax.swing.JPanel {
//en esta clase esta el fondo con botones y demas.
    /**
     * Creates new form ControlPanel
     */
    
    private ImageIcon background;
    private GameController gameController;
    
    public ControlPanel() {
        initComponents();
        this.background=new ImageIcon("./src/main/resources/imagenes/TableroFondo.png");
    }

    public void setController(GameController controller)
    {
        this.gameController=controller;
        this.listen(controller);
    }
    
    
    
    public void listen(ActionListener controller)
    {
        this.btnDado.addActionListener(controller);
        this.btnJugar.addActionListener(controller);
        this.btnPlayerOne.addActionListener(controller);
        this.btnPlayerTwo.addActionListener(controller);
        this.btnSalir.addActionListener(controller);
//        addMouseListener((MouseListener) controller);
    
    }
    
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        this.background.paintIcon(this, g, 0, 0);//es lo que dibuja el tablero
        if(gameController!=null)
        {
        this.gameController.draw(this, g);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPuntaje = new javax.swing.JLabel();
        btnPlayerTwo = new javax.swing.JButton();
        btnPlayerOne = new javax.swing.JButton();
        btnDado = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPuntaje.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtPuntaje.setText(" Puntuación:");
        add(txtPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        btnPlayerTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JugadorDos.png"))); // NOI18N
        btnPlayerTwo.setActionCommand("jugador2");
        btnPlayerTwo.setBorderPainted(false);
        btnPlayerTwo.setContentAreaFilled(false);
        add(btnPlayerTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 180, 210));

        btnPlayerOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JugadorUno.png"))); // NOI18N
        btnPlayerOne.setActionCommand("jugador1");
        btnPlayerOne.setBorderPainted(false);
        btnPlayerOne.setContentAreaFilled(false);
        add(btnPlayerOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, -1));

        btnDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dadoCuatro.png"))); // NOI18N
        btnDado.setActionCommand("dado");
        btnDado.setBorderPainted(false);
        btnDado.setContentAreaFilled(false);
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonJugar.png"))); // NOI18N
        btnJugar.setActionCommand("jugar");
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 130, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSalir.png"))); // NOI18N
        btnSalir.setActionCommand("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 140, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPlayerOne;
    private javax.swing.JButton btnPlayerTwo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel txtPuntaje;
    // End of variables declaration//GEN-END:variables
}
