/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.proyectoparchis.view;


import ucr.ac.cr.proyectoparchis.controller.GameController;

/**
 *
 * @author jeanmarco
 */
public class GUIGame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIGame.class.getName());

    /**
     * Creates new form GUIGame
     */
    public GUIGame(GameController controller) {
        initComponents();
        this.controlPanel.setController(controller);
        controller.setBoardPanel(boardPanel);
        this.boardPanel.setController(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardPanel = new ucr.ac.cr.proyectoparchis.view.BoardPanel();
        controlPanel = new ucr.ac.cr.proyectoparchis.view.ControlPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(boardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));
        getContentPane().add(controlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 910, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new GUIGame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.proyectoparchis.view.BoardPanel boardPanel;
    private ucr.ac.cr.proyectoparchis.view.ControlPanel controlPanel;
    // End of variables declaration//GEN-END:variables
}
