/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.proyectoparchis.view;

import java.awt.event.ActionListener;

/**
 *
 * @author jeanmarco
 */
public class VentanaDeSeleccionDeColor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaDeSeleccionDeColor.class.getName());

    /**
     * Creates new form VentanaDeSeleccionDeColor
     */
    public VentanaDeSeleccionDeColor() {
        initComponents();
    }
    
    public void listen(ActionListener controller)
    {
        this.btnAtras.addActionListener(controller);
        this.btnEnviar.addActionListener(controller);
    }
    
    public String getColorSeleccionado()
    {
        return (String)seleccionColor.getSelectedItem();//obtener el color seleccionado
    }
    
//    public String getColorCPU()
//    {
//        String color=getColorSeleccionado();
//        if(color.equalsIgnoreCase("Rojo"))//en caso de que sea rojo el color que se eligio, se le asigna amarillo al cPU
//        {
//            return "Amarillo";
//        }
//        else
//        {
//            if(color.equalsIgnoreCase("Amarillo"))//en caso de que sea amarillo el que se eligio, se le asigna rojo al cPU
//            {
//                return "Rojo";
//            }
//            else
//            {
//                if(color.equalsIgnoreCase("Azul"))//en caso de que sea azul el que se eligio, se le asigna verde al cPU
//                {
//                    return "Verde";
//                }
//                else
//                {
//                    
//                        return "Azul";//en caso de que verde el que se eligio, se le asigna azul al cPU
//
//                }
//            }
//                   
//        }
//    }
    
    public String getNombreJugador()
    {
        return this.txtNombreJugador1.getText();//obtener nombre Jugador
    }
    
    public String getNombreCPU()
    {
        return this.txtNombreCPU.getText();//obtener el nombre del cPU
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionColor = new javax.swing.JComboBox<>();
        lblSeleccionColor = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        lblNombreCPU = new javax.swing.JLabel();
        lblNombreJugador = new javax.swing.JLabel();
        txtNombreCPU = new javax.swing.JTextField();
        txtNombreJugador1 = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        lblImagenVentanaSeleccionColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seleccionColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amarillo", "Azul", "Rojo", "Verde" }));
        getContentPane().add(seleccionColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        lblSeleccionColor.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionColor.setText("Seleccion el color: ");
        getContentPane().add(lblSeleccionColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btnEnviar.setText("Enviar");
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        lblNombreCPU.setText("Nombre:");
        getContentPane().add(lblNombreCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        lblNombreJugador.setText("Nombre:");
        getContentPane().add(lblNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));
        getContentPane().add(txtNombreCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 90, -1));
        getContentPane().add(txtNombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 90, -1));

        btnAtras.setText("Atras");
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, 30));

        lblImagenVentanaSeleccionColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentanaSeleccion.png"))); // NOI18N
        lblImagenVentanaSeleccionColor.setText("jLabel1");
        getContentPane().add(lblImagenVentanaSeleccionColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 384, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaDeSeleccionDeColor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblImagenVentanaSeleccionColor;
    private javax.swing.JLabel lblNombreCPU;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JLabel lblSeleccionColor;
    private javax.swing.JComboBox<String> seleccionColor;
    private javax.swing.JTextField txtNombreCPU;
    private javax.swing.JTextField txtNombreJugador1;
    // End of variables declaration//GEN-END:variables
}
